a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from a_home.views import *
from a_users.views import profile_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('a_rtchat.urls')),
    path('profile/', include('a_users.urls')),
    path('@<username>/', profile_view, name='profile'),
]

# Only used in development
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

a_rtchat/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', chat_view, name='home'),
    path('chat/<username>', get_or_create_chatroom, name="start-chat"),
    path('chat/room/<chatroom_name>', chat_view, name="chatroom"),
    path('chat/new_groupchat/', create_groupchat, name="new-groupchat"),
    path('chat/edit/<chatroom_name>', chatroom_edit_view, name="edit-chatroom"),
    path('chat/delete/<chatroom_name>', chatroom_delete_view, name="chatroom-delete"),
    path('chat/leave/<chatroom_name>', chatroom_leave_view, name="chatroom-leave"),
    path('chat/fileupload/<chatroom_name>', chat_file_upload, name="chat-file-upload")
]

a_rtchat/models.py
import os

from django.contrib.auth.models import User
from django.db import models
import shortuuid

class ChatGroup(models.Model):
    group_name = models.CharField(max_length=128, unique=True, blank=True)
    groupchat_name = models.CharField(max_length=128, null=True, blank=True)
    admin = models.ForeignKey(User, related_name='groupchats', blank=True, null=True, on_delete=models.SET_NULL)
    users_online = models.ManyToManyField(User, related_name='online_in_groups', blank=True)
    members = models.ManyToManyField(User, related_name='chat_groups', blank=True)
    is_private = models.BooleanField(default=False)
    def __str__(self):
        return self.group_name

    def save(self, *args, **kwargs):
        if not self.groupchat_name:
            self.group_name = shortuuid.uuid()
        super().save(*args, **kwargs)

class GroupMessage(models.Model):
    group = models.ForeignKey(ChatGroup, related_name='chat_messages', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=300, blank=True, null=True)
    file = models.FileField(upload_to='files/', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def filename(self):
        if self.file:
            return os.path.basename(self.file.name)
        else:
            return None

    def __str__(self):
        if self.body:
            return f'{self.author.username} : {self.body}'
        elif self.file:
            return f'{self.author.username} : {self.filename}'

    class Meta:
        ordering = ['-created']

    @property
    def is_image(self):
        if self.filename.lower().endswith(('.jpg', '.jpeg', '.gif', '.svg', 'webp')):
            return True
        else:
            return False

a_rtchat/forms.py
from django.forms import ModelForm, TextInput
from django import forms
from .models import *


class ChatmessageCreateForm(ModelForm):
    class Meta:
        model = GroupMessage
        fields = ['body']
        widgets = {
            'body': forms.TextInput(attrs={'placeholder':'Add message...','class':'p-4 text-black', 'maxlength':'300','autofocus':True}),
        }

class NewGroupForm(ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name']
        widgets = {
            'groupchat_name': forms.TextInput(attrs={
                'placeholder': 'Add Name...',
                'class': 'p-4 text-black',
                'maxlength': '300',
                'autofocus': True,
            })
        }

class ChatRoomEditForm(ModelForm):
    class Meta:
        model = ChatGroup
        fields = ['groupchat_name']
        widgets = {
            'groupchat_name': forms.TextInput(attrs={
                'class': 'p-4 text-xl font-bold mb-4',
                'maxlength': '300',
            }),
        }

a_rtchat/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.contrib import messages


@login_required
def chat_view(request, chatroom_name='public-chat'):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    chat_messages = chat_group.chat_messages.all()[:30]
    form = ChatmessageCreateForm()
    other_user = None
    if chat_group.is_private:
        if request.user not in chat_group.members.all():
            raise Http404()

        for member in chat_group.members.all():
            if member != request.user:
                other_user = member
                break

    if chat_group.groupchat_name:
        if request.user not in chat_group.members.all():
            if request.user.emailaddress_set.filter(verified=True).exists():
                chat_group.members.add(request.user)
            else:
                messages.warning(request, 'You need to verify your email to join the chat!')
                return redirect('profile-settings')

    if request.htmx:
        form = ChatmessageCreateForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.author = request.user
            message.group = chat_group
            message.save()
            context = {
                'message':message,
                'user': request.user,
            }
            return render(request, 'a_rtchat/partials/chat_message_p.html', context)

    context = {
        'chat_messages': chat_messages,
        'form': form,
        'other_user': other_user,
        'chatroom_name': chatroom_name,
        'chat_group': chat_group
    }
    return render(request, 'a_rtchat/chat.html',context)


def get_or_create_chatroom(request, username):
    if request.user.username == username:
        return redirect('home')

    other_user = User.objects.get(username=username)
    my_chatrooms = request.user.chat_groups.filter(is_private=True)
    if my_chatrooms.exists():
        for chatroom in my_chatrooms:
            if other_user in chatroom.members.all():
                chatroom = chatroom
                break
            else:
                chatroom = ChatGroup.objects.create(is_private=True)
                chatroom.members.add(other_user, request.user)
    else:
        chatroom = ChatGroup.objects.create(is_private=True)
        chatroom.members.add(other_user, request.user)

    return redirect('chatroom', chatroom.group_name)

@login_required
def create_groupchat(request):
    form = NewGroupForm()

    if request.method == 'POST':
        form = NewGroupForm(request.POST)
        if form.is_valid():
            new_groupchat = form.save(commit=False)
            new_groupchat.admin = request.user
            new_groupchat.save()
            new_groupchat.members.add(request.user)
            return redirect('chatroom', new_groupchat.group_name)
    context = {
        'form': form
    }
    return render(request, 'a_rtchat/create_groupchat.html', context)

@login_required
def chatroom_edit_view(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    if request.user != chat_group.admin:
        raise Http404()

    form = ChatRoomEditForm(instance=chat_group)

    if request.method == 'POST':
        form = ChatRoomEditForm(request.POST, instance=chat_group)
        if form.is_valid():
            form.save()

            remove_members = request.POST.getlist('remove_members')
            for member_id in remove_members:
                member = User.objects.get(id=member_id)
                chat_group.members.remove(member)

            return redirect('chatroom', chatroom_name)
    context={
        'form': form,
        'chat_group': chat_group,
    }
    return render(request, 'a_rtchat/chatroom_edit.html', context)

@login_required
def chatroom_delete_view(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    if request.user != chat_group.admin:
        raise Http404()

    if request.method == 'POST':
        chat_group.delete()
        messages.success(request, 'Chatroom deleted')
        return redirect('home')

    return render(request, 'a_rtchat/chatroom_delete.html', {'chat_group':chat_group})


@login_required
def chatroom_leave_view(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)
    if request.user not in chat_group.members.all():
        raise Http404()

    if request.method == "POST":
        chat_group.members.remove(request.user)
        messages.success(request, "You left the chat")
        return redirect('home')


def chat_file_upload(request, chatroom_name):
    chat_group = get_object_or_404(ChatGroup, group_name=chatroom_name)

    if request.htmx and request.FILES:
        file = request.FILES['file']
        message = GroupMessage.objects.create(
            file=file,
            author=request.user,
            group=chat_group,
        )
        channel_layer = get_channel_layer()
        event = {
            'type': "message_handler",
            'message_id': message.id,
        }
        async_to_sync(channel_layer.group_send)(
            chatroom_name, event
        )
    return HttpResponse()

a_rtchat/templates/a_rtchat/chat.html
{% extends 'layouts/blank.html' %}
{% block content %}

<wrapper class="block max-w-2xl mx-auto my-10 px-6">
    {% if chat_group.groupchat_name %}
    <div class="flex justify-between">
        <h2>{{ chat_group.groupchat_name }}</h2>
        {% if user == chat_group.admin %}
        <a href="{% url 'edit-chatroom' chat_group.group_name %}"><div class="p-2 bg-gray-200 hover:bg-blue-600 rounded-lg group">
<svg class="fill-gray-500 group-hover:fill-white" width="16" height="16">
    <path d="M11.013 1.427a1.75 1.75 0 0 1 2.474 0l1.086 1.086a1.75 1.75 0 0 1 0 2.474l-8.61 8.61c-.21.21-.47.364-.756.445l-3.251.93a.75.75 0 0 1-.927-.928l.929-3.25c.081-.286.235-.547.445-.758l8.61-8.61Zm.176 4.823L9.75 4.81l-6.286 6.287a.253.253 0 0 0-.064.108l-.558 1.953 1.953-.558a.253.253 0 0 0 .108-.064Zm1.238-3.763a.25.25 0 0 0-.354 0L10.811 3.75l1.439 1.44 1.263-1.263a.25.25 0 0 0 0-.354Z"></path>
</svg>
</div></a>
        {% endif %}
    </div>
    {% endif %}
    <div id="chat_window" class="h-[45rem] flex flex-col bg-gray-800 rounded-2xl shadow-2xl relative p-1">
        <div class="flex justify-center text-emerald-400 bg-gray-800 p-2 sticky top-0 z-10">
            {% if other_user %}
            <div id="online-icon" class="gray-dot absolute top-2 left-2"></div>
            <a href="{% url 'profile' other_user.username %}">
                <div class="flex items-center gap-2 p-4 sticky top-0 z-10">
                    <img class="w-10 h-10 rounded-full object-cover" src="{{ other_user.profile.avatar }}" />
                    <div>
                        <span class="font-bold text-white">{{ other_user.profile.name }}</span>
                        <span class="text-sm font-light text-gray-400">@{{ other_user.username }}</span>
                    </div>
                </div>
            </a>
            {% elif chat_group.groupchat_name %}
            <ul id="groupchat-members" class="flex gap-4">
                {% for member in chat_group.members.all %}
                <li>
                    <a href="{% url 'profile' member.username %}" class="flex flex-col text-gray-400 items-center justify-center w-20 gap-2">
                        <img src="{{ member.profile.avatar }}" class="w-14 h-14 rounded-full object-cover" />
                        {{ member.profile.name|slice:":10" }}
                    </a>
                </li>
                {% endfor %}
            </ul>
            {%  else %}
            <div id="online-icon"></div>
            <span id="online-count" class="pr-1"></span> online
            {% endif %}
        </div>
        <div id='chat_container' class="overflow-y-auto grow">
            <ul id='chat_messages' class="flex flex-col justify-end gap-2 p-4">
                {% for message in chat_messages reversed %}
                {% include 'a_rtchat/chat_message.html' %}
                {% endfor %}
            </ul>
        </div>
        <div class="sticky bottom-0 z-10 p-2 bg-gray-800">
            <div class="flex flex-col gap-4 items-center rounded-xl px-2 py-2">
                <form id="chat_message_form" class="w-full"
                      hx-ext="ws"
                      ws-connect="/ws/chatroom/{{ chatroom_name }}"
                      ws-send="body.value"
                      _="on htmx:wsAfterSend reset() me">
                    {% csrf_token %}
                    {{form}}
                </form>
                <form id="chat_file_form" enctype="multipart/form-data" class="flex items-center w-full"
                    hx-post="{% url 'chat-file-upload' chat_group.group_name %}"
                    hx-target="#chat_messages" hx-swap="beforeend"
                    _="on htmx:beforeSend reset() me">
                    {% csrf_token %}
                    <input type="file" name="file" id="id_file" class="!bg-transparent text-gray-400">
                    <button type="submit" class="whitespace-nowrap !text-sm !py-3 !px-4 h-fit">Submit file</button>
                </form>
            </div>
        </div>
    </div>
    {% if chat_group.members.exists %}
    <a href="{% url 'chatroom-leave' chat_group.group_name %}"></a>
    </br>
    {% include 'a_rtchat/partials/model_chat_leave.html' %}
    {% endif %}
</wrapper>

{% endblock %}

{% block javascript %}
<script>
    function scrollToBottom(time=0) {
        setTimeout(function(){
            const container = document.getElementById('chat_container');
            container.scrollTop = container.scrollHeight;
            }, time);
    }
    scrollToBottom();

    document.body.addEventListener('htmx:wsAfterMessage', function(evt) {
        scrollToBottom();
    });
</script>
{% endblock %}

a_rtchat/templates/a_rtchat/chat_message.html
{% if message.author == user %}
<li class="flex justify-end mb-4">
    <div class="bg-green-200 rounded-l-lg rounded-tr-lg p-4 max-w-[75%]">
        {% include 'a_rtchat/partials/message_content.html' %}
    </div>
    <div class="flex items-end">
        <svg height="13" width="8" >
            <path fill="#bbf7d0" d="M6.3,10.4C1.5,8.7,0.9,5.5,0,0.2L0,13l5.2,0C7,13,9.6,11.5,6.3,10.4z"/>
        </svg>
    </div>
</li>
{% else %}
<li>
    <div class="flex justify-start">
        <div class="flex items-end mr-2" >
            <a href="{% url 'profile' message.author.username %}">
                <div class="relative">
                    <div id="user-{{message.author.id}}"></div>
                    <img class="w-8 h-8 rounded-full object-cover" src="{{ message.author.profile.avatar}}">
                </div>
            </a>
        </div>
        <div class="flex items-end" >
            <svg height="13" width="8" >
                <path fill="white" d="M2.8,13L8,13L8,0.2C7.1,5.5,6.5,8.7,1.7,10.4C-1.6,11.5,1,13,2.8,13z"></path>
            </svg>
        </div>
        <div class="bg-white p-4 max-w-[75%] rounded-r-lg rounded-tl-lg">
            {% include 'a_rtchat/partials/message_content.html' %}
        </div>
    </div>
    <div class="text-sm font-light py-1 ml-10">
        <span class="text-white">{{message.author.profile.name}}</span>
        <span class="text-gray-400">@{{ message.author.username}}</span>
    </div>
</li>
{% endif %}

a_rtchat/templates/a_rtchat/chatroom_delete.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1>Delete this chatroom?</h1>

<h2>"{{ chat_group.groupchat_name}}"</h2>
<form method="POST">
    {% csrf_token %}
    <button type="submit" class="button-red mt-4">Yes, delete</button>
    <a class="button button-gray ml-1" hred="{{ request.META.HTTP_REFERER }}">Cancel</a>
</form>
{% endblock %}

a_rtchat/templates/a_rtchat/chatroom_edit.html
{% extends 'layouts/box.html' %}

{% block content %}

<h1>Edit Chat</h1>

<form method="post">
    {% csrf_token %}
    {{ form }}

    <div class="my-4">
    <h2>Members</h2>
    {% for member in chat_group.members.all %}
    <div class="flex justify-between items-center">
        <div class="flex items-center gap-2 py-2">
            <img class="w-14 h-14 rounded-full object-cover" src="{{ member.profile.avatar }}" />
            <div>
                <span class="font-bold">{{ member.profile.name }}</span>
                <span class="text-sm font-light text-gray-600">@{{ member.username }}</span>
            </div>
        </div>

        {% if member != chat_group.admin %}
        <div class="inline-block pr-4">
            <input type="checkbox" name="remove_members" value="{{ member.id }}" class="relative p-5 cursor-pointer appearance-none rounded-md border after:absolute after:left-0 after:top-0 after:h-full after:w-full after:bg-[url('https://img.icons8.com/ffffff/32/multiply.png')] after:bg-center checked:bg-red-500 hover:ring hover:ring-gray-300 focus:outline-none" />
        </div>
        {% endif %}
    </div>
    {% endfor %}
    </div>

    <button class="mt-2" type="submit">Update</button>
</form>

<a href="{% url 'chatroom-delete' chat_group.group_name %}" class="flex justify-end mt-4 text-gray-400 hover:text-red-500" >Delete Chatroom</a>

{% endblock %}

a_rtchat/templates/a_rtchat/create_groupchat.html
{% extends 'layouts/box.html' %}
{% block content %}
<h1>New Group Chat</h1>
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button class="mt-2" type="submit">Create Group Chat</button>
</form>
{% endblock %}